language: node_js

node_js:
  - "6"

env:
  - NODE_ENV = "test"

before_script:
  - npm install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - npm run test

services: mongodb
